### PR TITLE
Add host:ro filesystem permission

### PR DESCRIPTION
**Pull request by j8r**
Allows to read data from Disk/USB drive mounts.

### CODE REVIEW

**Comment by rderooy** [comment]
To be honest I had thought of something like that when I originally wrote the manifest, but did not do it as it goes against the idea that flatpaks are sandboxed. This gives it ro on almost the entire filesystem, which would be similar to what a non-sandboxed application would have.

What I would like to see, is a way to say, add support for hotplug storage like a USB drive. But this would need to be added at the sandbox level.

**Comment by hfiguiere** [comment]
`--filesystem=/run/media` and `--filesystem=/media` ought to be enough to access media. (you can add the `:ro`)

**Comment by j8r** [comment]
The sandbox runs as the user, right? Why not give access to the whole filesystem, and let the classic UNIX ownership and permissions handle the security?

Also I've taken the USB drive as an example, but I have other mounts on my filesystem, on in /mnt in particular.

**Comment by j8r** [comment]
The sandbox runs as the user, right? Why not give access to the whole filesystem, and let the classic UNIX ownership and permissions handle the security?

Also I've taken the USB drive as an example, but I have other mounts on my filesystem, one in /mnt in particular.

**Comment by j8r** [comment]
Tell me if I'm wrong, I don't see what this filesystem permissions can bring much if the sandbox already can read/write the whole home directory, which is certainly the most likely place to have sensitive personal information... The other system locations are at most read-only, and sensitive locations are not readable at all (list /etc/passwd).

**Comment by j8r** [comment]
Tell me if I'm wrong, I don't see what this filesystem permissions can bring much if the sandbox already can read/write the whole home directory, which is certainly the most likely place to have sensitive personal information... On UNIX the sensitive system locations are already not readable at all (like /etc/passwd), or read-only if not.

**Comment by j8r** [comment]
Anything unclear from what I said @rderooy or @hfiguiere? I think this permission is fine security-wise.

**Comment by rderooy** [comment]
@j8r I will not accept this PR, as it is against the principle of a sandbox. If you wish to widen the permissions, you can do it for your local installation as mentioned in the README.md

e.g. to allow access to /run/media:

```
flatpak override --filesystem=/run/media com.dosbox_x.DOSBox-X
```

**Comment by j8r** [comment]
Having the whole gome directory in read is not against? I don't really get it...

**Comment by j8r** [comment]
Having the whole home directory, with ou personal data, pictures etc in read **and** write is not against? I don't really get it...

**Comment by j8r** [comment]
Sorry, it is even read and write, so that's even worse!

**Comment by j8r** [comment]
An attacker can already escape the sandbox easily by adding stuff inside `.bashrc` for example, so why bother here? There is already a big security hole already in the sandbox regarding the filesystem.

**Pull request closed without merging**
